# Generated by Django 6.0.4 on 2026-05-26 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingtier',
            options={'ordering': ['lessons_per_month']},
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan'),
        ),
        migrations.AlterUniqueTogether(
            name='pricingtier',
            unique_together={('plan', 'lessons_per_month')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsubscription',
            unique_together={('student', 'plan', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('name', 'branch')},
        ),
        migrations.AlterModelTable(
            name='pricingtier',
            table='subscriptions_pricingtier',
        ),
        migrations.AlterModelTable(
            name='studentsubscription',
            table='subscriptions_studentsubscription',
        ),
        migrations.AlterModelTable(
            name='subscriptionplan',
            table='subscriptions_subscriptionplan',
        ),
    ]
